In [1]:
import numpy as np
import torch

import pandas as pd

In [2]:
from data_2.har.har_datasets import load_dataset

In [3]:
from data_2.har.label_mappings import ucihar_label_mapping

In [4]:
from data_2.base import STSDataset

In [5]:
dt = load_dataset("./datasets/UCI-HAPT")

In [6]:
dataset = STSDataset(dt, 10, 1, None, None, ucihar_label_mapping)

In [7]:
dataset.splits

array([      0,   20598,   39884,   57910,   74475,   95469,  112962,
        130630,  146518,  163382,  178420,  194942,  227031,  244226,
        260254,  275804,  292160,  308404,  324025,  339764,  351365,
        361263,  377700,  394230,  410862,  427022,  444823,  462007,
        479470,  496029,  513208,  530386,  551458,  572597,  593900,
        613435,  635834,  655892,  674991,  692828,  712521,  730484,
        751290,  770774,  788706,  806258,  826323,  844309,  865031,
        884457,  905687,  926039,  946717,  967033,  985286, 1004201,
       1024757, 1043593, 1062244, 1080152, 1103690, 1122772])

In [8]:
dataset.labels.shape

(1122772,)

In [9]:
ids, classes = dataset.getSameClassWindowIndex()

In [17]:
ids_CP = dataset.getChangePointIndex()

In [18]:
ids_CP

array([   982,   1142,   1944, ..., 814204, 814909, 815613])

In [19]:
dataset.indices[9]

259

In [13]:
classes

array([4, 4, 4, ..., 1, 1, 1])

In [11]:
len(dataset)

815614

In [15]:
classes[1000]

6

In [21]:
dataset[983]

(array([[0.75331473, 0.50354082, 0.50363902, 0.49748134, 0.50024437,
         0.50047313],
        [0.75331473, 0.5031681 , 0.50327512, 0.49717419, 0.50056512,
         0.50033577],
        [0.75331473, 0.50242267, 0.50109171, 0.49660595, 0.5005804 ,
         0.50053418],
        [0.75261689, 0.5031681 , 0.50072781, 0.49628344, 0.50105388,
         0.50067154],
        [0.75331473, 0.50242267, 0.50181952, 0.49623737, 0.50123716,
         0.50047313],
        [0.75401257, 0.50242267, 0.50145562, 0.49634487, 0.50258125,
         0.50122099],
        [0.75540825, 0.50055908, 0.50218342, 0.49525448, 0.50432245,
         0.50125152],
        [0.75191906, 0.5009318 , 0.4967249 , 0.4966981 , 0.50213831,
         0.50061049],
        [0.75157014, 0.50130452, 0.4970888 , 0.49858709, 0.50065676,
         0.50086996],
        [0.75296581, 0.49534104, 0.4959971 , 0.50067574, 0.50218413,
         0.49996947]]),
 array([4, 4, 4, 4, 4, 4, 4, 4, 4, 6]))